import PropTypes from 'prop-types'
export const propTypes = {
    color: PropTypes.oneOf([
        'initial',
        'inherit',
        'textPrimary',
        'textSecondary',
        'textGrey',
        'error',
        'primary',
        'secondary',
        'accent',
        'grey',
        'white',
        'black',
        'cyan',
        'mediumgrey',
        'lightgrey',
        'darkgrey',
        'red',
        'warn',
    ]),
    variant: PropTypes.oneOf([
        'subtitle1',
        'subtitle2',
        'caption',
        'button',
        'overline',
        'srOnly',
        'inherit',
        'body1',
        'body2',
        'body3',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'caption',
        'customNumber',
    ]),
    weight: PropTypes.oneOf(['light', 'regular', 'medium', 'bold']),
    underline: PropTypes.bool,
    overflowEllipsis: PropTypes.bool,
    align: PropTypes.oneOf(['left', 'center', 'right', 'justify']),
    numberOfLines: PropTypes.number,
    fullWidth: PropTypes.bool,
}

export const defaultProps = {
    color: undefined,
    fullWidth: true,
    variant: 'body1',
    weight: 'regular',
    underline: false,
    overflowEllipsis: false,
    align: undefined,
    numberOfLines: undefined,
}
