# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Create AppIcon"
  lane :generate_icon do
    appicon(
      appicon_devices: [:iphone],
      appicon_path: 'appMovie/Images.xcassets'
    )
  end

  desc "Create Splash"
  lane :splash_screen do
    appicon(
      appicon_image_file: 'fastlane/metadata/splash_screen.jpeg',
      appicon_devices: [:universal],
      appicon_path: "appMovie/Assets.xcassets",
      appicon_name: 'Splash.imageset'
    )
  end
end
