# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Create AppIcon"
  lane :generate_icon do
    android_appicon(
      appicon_image_file: 'fastlane/metadata/app_icon.png',
      appicon_icon_types: [:launcher],
      appicon_path: 'app/src/main/res/mipmap'
    )
  end
  
  desc "Create Splash"
  lane :splash_screen do
    android_appicon(
      appicon_image_file: 'fastlane/metadata/splash_screen.jpeg',
      appicon_icon_types: [:splash_port],
      appicon_path: 'app/src/main/res/drawable',
      appicon_filename: 'splash_icon'
    )
  end
end
